[tool.pyright]
analyzeUnannotatedFunctions = false
reportUnnecessaryCast = "information"
reportUnnecessaryTypeIgnoreComment = "information"
reportUnusedExpression = false
typeCheckingMode = "basic"
useLibraryCodeForTypes = true

[tool.ruff]
line-length = 100
target-version = "py313"
unsafe-fixes = false

[tool.ruff.lint]
select = [
  "A",
  "B",
  "C401",
  "C417",
  "D205",
  "D209",
  "E741",
  "EM",
  "F841",
  "FBT",
  "G004",
  "I",
  "N806",
  "PLR0402",
  "PLR1722",
  "PT018",
  "PTH",
  "PYI036",
  "RET502",
  "RUF100",
  "S113",
  "SIM105",
  "SIM108",
  "TRY201",
  "UP",
]

[tool.ruff.lint.isort]
case-sensitive = true
